/**
 * communityRates.js — Built-in community rate profiles from well-known FPV pilots.
 * These are hardcoded and NOT saved to localStorage.
 */

export const RATE_TYPES = [
  { id: 'betaflight', label: 'Betaflight',  params: ['rc_rate', 'rate', 'rc_expo'] },
  { id: 'raceflight', label: 'Raceflight',  params: ['rc_rate', 'rate', 'rc_expo'] },
  { id: 'kiss',       label: 'KISS',        params: ['rc_rate', 'rate', 'rc_expo'] },
  { id: 'actual',     label: 'Actual',      params: ['center_sensitivity', 'max_rate', 'expo'] },
  { id: 'quick',      label: 'QuickRates',  params: ['rc_rate', 'rate', 'rc_expo'] },
];

export const QUAD_TYPES = [
  { value: 'freestyle', label: 'Freestyle' },
  { value: 'racing',    label: 'Racing' },
  { value: 'cinematic', label: 'Cinematic' },
  { value: 'longrange', label: 'Long Range' },
  { value: 'whoop',     label: 'Whoop' },
];

export const COMMUNITY_RATES = [
  // ── FREESTYLE PILOTS ───────────────────────────────────────────
  {
    id: 'oscarliang-thumbing', name: 'Freestyle Thumbing', pilotName: 'Oscar Liang',
    website: 'oscarliang.com', quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['freestyle', 'thumbing', 'smooth', 'beginner-friendly'],
    notes: 'Great all-around freestyle rates. Smooth center, good max rate for tricks.',
    roll: { center_sensitivity: 180, max_rate: 670, expo: 0.0 },
    pitch: { center_sensitivity: 180, max_rate: 670, expo: 0.0 },
    yaw: { center_sensitivity: 120, max_rate: 500, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'oscarliang-pinching', name: 'Freestyle Pinching', pilotName: 'Oscar Liang',
    website: 'oscarliang.com', quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['freestyle', 'pinching', 'precise'],
    notes: 'Higher center sensitivity for pinchers — more accurate fine movements.',
    roll: { center_sensitivity: 220, max_rate: 670, expo: 0.0 },
    pitch: { center_sensitivity: 220, max_rate: 670, expo: 0.0 },
    yaw: { center_sensitivity: 140, max_rate: 500, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'jbardwell-flow', name: 'Flow Rates', pilotName: 'Joshua Bardwell',
    website: 'youtube.com/@JoshuaBardwell', quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['flow', 'smooth', 'medium', 'popular'],
    notes: 'Very popular rates. Smooth feel, good for learning freestyle.',
    roll: { rc_rate: 1.0, rate: 0.7, expo: 0.15 },
    pitch: { rc_rate: 1.0, rate: 0.7, expo: 0.15 },
    yaw: { rc_rate: 1.0, rate: 0.5, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'mrsteele-juicy', name: 'Juicy Rates', pilotName: 'Mr. Steele',
    website: 'youtube.com/@MrSteeleFPV', quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['juicy', 'freestyle', 'snap', 'high-rate', 'advanced'],
    notes: 'High rate, snap feel. Classic Mr. Steele style for juicy freestyle.',
    roll: { rc_rate: 1.2, rate: 0.73, expo: 0.0 },
    pitch: { rc_rate: 1.2, rate: 0.73, expo: 0.0 },
    yaw: { rc_rate: 1.0, rate: 0.5, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'mrsteele-actual', name: 'Steele Actual', pilotName: 'Mr. Steele',
    website: 'youtube.com/@MrSteeleFPV', quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['flow', 'actual', 'freestyle'],
    notes: 'Steele\'s Actual rate setup for flowing freestyle.',
    roll: { center_sensitivity: 200, max_rate: 670, expo: 0.0 },
    pitch: { center_sensitivity: 200, max_rate: 670, expo: 0.0 },
    yaw: { center_sensitivity: 150, max_rate: 400, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'ledrib-flow', name: 'Flow Freestyle', pilotName: 'Le Drib',
    website: 'youtube.com/@LeDrib', quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['flow', 'smooth', 'hangtime', 'buttery'],
    notes: 'Known for buttery smooth flow lines. Lower max rate, high expo.',
    roll: { center_sensitivity: 160, max_rate: 620, expo: 0.15 },
    pitch: { center_sensitivity: 160, max_rate: 620, expo: 0.15 },
    yaw: { center_sensitivity: 100, max_rate: 440, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.2, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'ledrib-cinematic', name: 'Cinematic Smooth', pilotName: 'Le Drib',
    website: 'youtube.com/@LeDrib', quadType: 'cinematic', rateType: 'betaflight', source: 'community',
    tags: ['cinematic', 'smooth', 'filming'],
    notes: 'Super smooth rates for cinematic flying. Low rates, high expo for precision.',
    roll: { rc_rate: 0.8, rate: 0.65, expo: 0.3 },
    pitch: { rc_rate: 0.8, rate: 0.65, expo: 0.3 },
    yaw: { rc_rate: 0.7, rate: 0.45, expo: 0.1 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'nytfury-sbang', name: 'Sbang Style', pilotName: 'Nytfury',
    website: 'youtube.com/@Nytfury', quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['sbang', 'snap', 'high-rate', 'aggressive', 'advanced'],
    notes: 'Very high rate for sbang style. Full stick very fast — for experts only.',
    roll: { rc_rate: 1.35, rate: 0.75, expo: 0.0 },
    pitch: { rc_rate: 1.35, rate: 0.75, expo: 0.0 },
    yaw: { rc_rate: 1.0, rate: 0.5, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'ummagawd-freestyle', name: 'Umma Rates', pilotName: 'Ummagawd',
    website: 'youtube.com/@ummagawd', quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['freestyle', 'medium', 'versatile'],
    notes: 'Versatile rates good for both freestyle and casual flying.',
    roll: { rc_rate: 1.1, rate: 0.68, expo: 0.1 },
    pitch: { rc_rate: 1.1, rate: 0.68, expo: 0.1 },
    yaw: { rc_rate: 1.0, rate: 0.5, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'rotorriot-freestyle', name: 'Rotor Riot Freestyle', pilotName: 'Rotor Riot',
    website: 'youtube.com/@RotorRiot', quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['freestyle', 'popular', 'beginner-friendly'],
    notes: 'Team Rotor Riot rates — great all-around starting point.',
    roll: { rc_rate: 1.05, rate: 0.72, expo: 0.1 },
    pitch: { rc_rate: 1.05, rate: 0.72, expo: 0.1 },
    yaw: { rc_rate: 1.0, rate: 0.5, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'fpvknowitall-medium', name: 'Balanced Freestyle', pilotName: 'FPV Know It All',
    quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['balanced', 'freestyle', 'medium'],
    notes: 'Balanced rates for general freestyle. Not too snappy, not too soft.',
    roll: { center_sensitivity: 200, max_rate: 700, expo: 0.0 },
    pitch: { center_sensitivity: 200, max_rate: 700, expo: 0.0 },
    yaw: { center_sensitivity: 130, max_rate: 470, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'shaggyfpv-flow', name: 'Flow Lines', pilotName: 'Shaggy FPV',
    quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['flow', 'smooth', 'cinematic-ish'],
    notes: 'Shaggy flow style — smooth arcs, lower center sensitivity.',
    roll: { rc_rate: 0.9, rate: 0.65, expo: 0.2 },
    pitch: { rc_rate: 0.9, rate: 0.65, expo: 0.2 },
    yaw: { rc_rate: 0.9, rate: 0.45, expo: 0.1 },
    thr_mid: 0.5, thr_expo: 0.15, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'supafly-betaflight', name: 'SupaFly BF Rates', pilotName: 'SupaFly FPV',
    website: 'supaflyfpv.com', quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['freestyle', 'classic', 'balanced'],
    notes: 'Classic Betaflight rates from SupaFly. High expo, no superrate.',
    roll: { rc_rate: 2.2, rate: 0.0, expo: 0.75 },
    pitch: { rc_rate: 2.2, rate: 0.0, expo: 0.75 },
    yaw: { rc_rate: 2.12, rate: 0.0, expo: 0.75 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'supafly-kiss', name: 'SupaFly KISS Rates', pilotName: 'SupaFly FPV',
    website: 'supaflyfpv.com', quadType: 'freestyle', rateType: 'kiss', source: 'community',
    tags: ['kiss', 'freestyle', 'classic'],
    notes: 'KISS rates version from SupaFly community.',
    roll: { rc_rate: 1.3, rate: 0.75, expo: 0.35 },
    pitch: { rc_rate: 1.3, rate: 0.75, expo: 0.35 },
    yaw: { rc_rate: 1.3, rate: 0.65, expo: 0.35 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'johnnyfpv-cine', name: 'JohnnyFPV Cine', pilotName: 'JohnnyFPV',
    website: 'youtube.com/@JohnnyFPV', quadType: 'cinematic', rateType: 'actual', source: 'community',
    tags: ['cinematic', 'smooth', 'pro'],
    notes: 'Professional cinematic rates. Extremely smooth transitions for filming.',
    roll: { center_sensitivity: 140, max_rate: 500, expo: 0.15 },
    pitch: { center_sensitivity: 140, max_rate: 500, expo: 0.15 },
    yaw: { center_sensitivity: 100, max_rate: 350, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'johnnyfpv-freestyle', name: 'JohnnyFPV Freestyle', pilotName: 'JohnnyFPV',
    website: 'youtube.com/@JohnnyFPV', quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['freestyle', 'smooth', 'pro', 'film'],
    notes: 'JohnnyFPV freestyle setup — buttery smooth yet capable of tricks.',
    roll: { center_sensitivity: 170, max_rate: 650, expo: 0.1 },
    pitch: { center_sensitivity: 170, max_rate: 650, expo: 0.1 },
    yaw: { center_sensitivity: 110, max_rate: 420, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.1, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'skitzo-freestyle', name: 'Skitzo Rates', pilotName: 'Skitzo',
    website: 'youtube.com/@SkitzoFPV', quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['freestyle', 'aggressive', 'snap', 'advanced'],
    notes: 'Aggressive freestyle rates with quick snap capability.',
    roll: { rc_rate: 1.15, rate: 0.75, expo: 0.05 },
    pitch: { rc_rate: 1.15, rate: 0.75, expo: 0.05 },
    yaw: { rc_rate: 1.05, rate: 0.55, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'nurk-freestyle', name: 'Nurk Freestyle', pilotName: 'Nurk FPV',
    website: 'youtube.com/@NurkFPV', quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['freestyle', 'flow', 'precision'],
    notes: 'Precision freestyle rates. Great for technical gaps and matty flips.',
    roll: { center_sensitivity: 190, max_rate: 680, expo: 0.0 },
    pitch: { center_sensitivity: 190, max_rate: 680, expo: 0.0 },
    yaw: { center_sensitivity: 130, max_rate: 450, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'ethix-freestyle', name: 'Ethix Freestyle', pilotName: 'Ethix / TBS',
    website: 'ethix.com', quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['freestyle', 'ethix', 'smooth'],
    notes: 'Ethix team recommended freestyle rates. Smooth and reliable.',
    roll: { rc_rate: 1.0, rate: 0.72, expo: 0.12 },
    pitch: { rc_rate: 1.0, rate: 0.72, expo: 0.12 },
    yaw: { rc_rate: 1.0, rate: 0.5, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'botgrinder-urban', name: 'Urban Freestyle', pilotName: 'BotGrinder',
    website: 'youtube.com/@BotGrinder', quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['urban', 'freestyle', 'precise', 'tight-gaps'],
    notes: 'Precise rates for urban bando flying. Good center control for tight gaps.',
    roll: { center_sensitivity: 210, max_rate: 650, expo: 0.05 },
    pitch: { center_sensitivity: 210, max_rate: 650, expo: 0.05 },
    yaw: { center_sensitivity: 140, max_rate: 460, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'vanover-race', name: 'Vanover DRL', pilotName: 'Alex Vanover',
    website: 'youtube.com/@AlexVanover', quadType: 'racing', rateType: 'betaflight', source: 'community',
    tags: ['racing', 'DRL', 'champion', 'precise'],
    notes: 'DRL champion rates. High authority for competitive racing.',
    roll: { rc_rate: 1.4, rate: 0.7, expo: 0.0 },
    pitch: { rc_rate: 1.4, rate: 0.7, expo: 0.0 },
    yaw: { rc_rate: 1.2, rate: 0.5, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  // ── RACING PILOTS ──────────────────────────────────────────────
  {
    id: 'quadmovr-race', name: 'Race Rates', pilotName: 'QuadMovr',
    website: 'youtube.com/@QuadMovr', quadType: 'racing', rateType: 'actual', source: 'community',
    tags: ['racing', 'precise', 'low-expo', 'high-center'],
    notes: 'High center sensitivity for gate precision. Lower max rate than freestyle.',
    roll: { center_sensitivity: 230, max_rate: 600, expo: 0.0 },
    pitch: { center_sensitivity: 230, max_rate: 600, expo: 0.0 },
    yaw: { center_sensitivity: 160, max_rate: 450, expo: 0.0 },
    thr_mid: 0.45, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'race-classic-low', name: 'Classic Race Low', pilotName: 'Generic Race',
    quadType: 'racing', rateType: 'actual', source: 'community',
    tags: ['racing', 'low-rate', 'precise', 'gates'],
    notes: 'Low max rate for precise gate flying. Standard race setup.',
    roll: { center_sensitivity: 200, max_rate: 450, expo: 0.0 },
    pitch: { center_sensitivity: 200, max_rate: 450, expo: 0.0 },
    yaw: { center_sensitivity: 140, max_rate: 360, expo: 0.0 },
    thr_mid: 0.45, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'race-betaflight-standard', name: 'Race BF Standard', pilotName: 'Generic Race',
    quadType: 'racing', rateType: 'betaflight', source: 'community',
    tags: ['racing', 'betaflight', 'linear', 'standard'],
    notes: 'Standard Betaflight racing rates. Linear, predictable.',
    roll: { rc_rate: 0.9, rate: 0.38, expo: 0.0 },
    pitch: { rc_rate: 0.9, rate: 0.38, expo: 0.0 },
    yaw: { rc_rate: 0.9, rate: 0.3, expo: 0.0 },
    thr_mid: 0.45, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'drl-race-style', name: 'DRL Style', pilotName: 'DRL Generic',
    quadType: 'racing', rateType: 'actual', source: 'community',
    tags: ['racing', 'DRL', 'league-racing', 'precise'],
    notes: 'Drone Racing League-inspired setup. Low and precise.',
    roll: { center_sensitivity: 180, max_rate: 500, expo: 0.0 },
    pitch: { center_sensitivity: 180, max_rate: 500, expo: 0.0 },
    yaw: { center_sensitivity: 120, max_rate: 380, expo: 0.0 },
    thr_mid: 0.45, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'miniquad-race-high', name: 'Race High Authority', pilotName: 'Generic Race',
    quadType: 'racing', rateType: 'actual', source: 'community',
    tags: ['racing', 'high-authority', 'fast-correction'],
    notes: 'Higher rates for aggressive race lines. Fast correction needed.',
    roll: { center_sensitivity: 250, max_rate: 700, expo: 0.0 },
    pitch: { center_sensitivity: 250, max_rate: 700, expo: 0.0 },
    yaw: { center_sensitivity: 170, max_rate: 500, expo: 0.0 },
    thr_mid: 0.45, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'race-kiss-classic', name: 'KISS Race Classic', pilotName: 'Community',
    quadType: 'racing', rateType: 'kiss', source: 'community',
    tags: ['KISS', 'racing', 'classic'],
    notes: 'Classic KISS rate curve for racing. Sharp center, controlled endpoints.',
    roll: { rc_rate: 0.7, rate: 0.8, expo: 0.15 },
    pitch: { rc_rate: 0.7, rate: 0.8, expo: 0.15 },
    yaw: { rc_rate: 0.6, rate: 0.5, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'race-quick-rates', name: 'Quick Race Setup', pilotName: 'Community',
    quadType: 'racing', rateType: 'quick', source: 'community',
    tags: ['racing', 'quickrates', 'simple'],
    notes: 'QuickRates system for racing. Simple to tune, predictable.',
    roll: { rc_rate: 0.8, rate: 0.65, expo: 0.0 },
    pitch: { rc_rate: 0.8, rate: 0.65, expo: 0.0 },
    yaw: { rc_rate: 0.7, rate: 0.5, expo: 0.0 },
    thr_mid: 0.45, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  // ── CINEMATIC PILOTS ───────────────────────────────────────────
  {
    id: 'cinematic-slow', name: 'Cinematic Smooth', pilotName: 'Generic Cine',
    quadType: 'cinematic', rateType: 'actual', source: 'community',
    tags: ['cinematic', 'smooth', 'slow', 'ultra-smooth'],
    notes: 'Ultra smooth for cinematic shots. Very low center sensitivity.',
    roll: { center_sensitivity: 100, max_rate: 400, expo: 0.4 },
    pitch: { center_sensitivity: 100, max_rate: 400, expo: 0.4 },
    yaw: { center_sensitivity: 80, max_rate: 300, expo: 0.3 },
    thr_mid: 0.5, thr_expo: 0.4, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cinewhoop-smooth', name: 'Cinewhoop Rates', pilotName: 'Generic Cinewhoop',
    quadType: 'cinematic', rateType: 'actual', source: 'community',
    tags: ['cinewhoop', 'indoor', 'smooth', 'filming'],
    notes: 'Low rates for cinewhoop indoor flying. Very controlled.',
    roll: { center_sensitivity: 120, max_rate: 380, expo: 0.3 },
    pitch: { center_sensitivity: 120, max_rate: 380, expo: 0.3 },
    yaw: { center_sensitivity: 100, max_rate: 300, expo: 0.2 },
    thr_mid: 0.55, thr_expo: 0.3, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cinematic-bf-smooth', name: 'Cine BF Smooth', pilotName: 'Generic Cine',
    quadType: 'cinematic', rateType: 'betaflight', source: 'community',
    tags: ['cinematic', 'betaflight', 'smooth', 'filming'],
    notes: 'Betaflight cinematic rates with high expo for center softness.',
    roll: { rc_rate: 0.75, rate: 0.6, expo: 0.35 },
    pitch: { rc_rate: 0.75, rate: 0.6, expo: 0.35 },
    yaw: { rc_rate: 0.65, rate: 0.4, expo: 0.15 },
    thr_mid: 0.5, thr_expo: 0.3, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cinematic-reelsteady', name: 'ReelSteady Cine', pilotName: 'Community',
    quadType: 'cinematic', rateType: 'actual', source: 'community',
    tags: ['cinematic', 'reelsteady', 'stabilized', 'filming'],
    notes: 'Optimized for ReelSteady/Gyroflow stabilization. Slow deliberate moves.',
    roll: { center_sensitivity: 90, max_rate: 350, expo: 0.5 },
    pitch: { center_sensitivity: 90, max_rate: 350, expo: 0.5 },
    yaw: { center_sensitivity: 70, max_rate: 280, expo: 0.3 },
    thr_mid: 0.5, thr_expo: 0.4, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cinematic-orbits', name: 'Orbit Master', pilotName: 'Community',
    quadType: 'cinematic', rateType: 'actual', source: 'community',
    tags: ['cinematic', 'orbits', 'smooth', 'panning'],
    notes: 'Very low yaw for smooth orbits and panning shots.',
    roll: { center_sensitivity: 110, max_rate: 420, expo: 0.3 },
    pitch: { center_sensitivity: 110, max_rate: 420, expo: 0.3 },
    yaw: { center_sensitivity: 60, max_rate: 220, expo: 0.4 },
    thr_mid: 0.5, thr_expo: 0.3, createdAt: '2024-01-01T00:00:00.000Z',
  },
  // ── WHOOP / MICRO ──────────────────────────────────────────────
  {
    id: 'oscarliang-whoop', name: 'Tiny Whoop Indoor', pilotName: 'Oscar Liang',
    website: 'oscarliang.com', quadType: 'whoop', rateType: 'actual', source: 'community',
    tags: ['whoop', 'indoor', 'micro', 'tiny'],
    notes: 'Higher yaw rate for indoor whooping — lots of rapid turns needed.',
    roll: { center_sensitivity: 150, max_rate: 550, expo: 0.0 },
    pitch: { center_sensitivity: 150, max_rate: 550, expo: 0.0 },
    yaw: { center_sensitivity: 180, max_rate: 650, expo: 0.0 },
    thr_mid: 0.6, thr_expo: 0.3, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'whoop-outdoor', name: 'Outdoor Whoop', pilotName: 'Community',
    quadType: 'whoop', rateType: 'betaflight', source: 'community',
    tags: ['whoop', 'outdoor', '75mm', 'casual'],
    notes: 'Outdoor whoop rates — moderate rates for parks and gardens.',
    roll: { rc_rate: 1.0, rate: 0.65, expo: 0.1 },
    pitch: { rc_rate: 1.0, rate: 0.65, expo: 0.1 },
    yaw: { rc_rate: 1.1, rate: 0.55, expo: 0.0 },
    thr_mid: 0.55, thr_expo: 0.2, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'whoop-race', name: 'Whoop Race', pilotName: 'Community',
    quadType: 'whoop', rateType: 'actual', source: 'community',
    tags: ['whoop', 'racing', 'indoor-race', 'fast'],
    notes: 'Whoop racing rates — fast yaw, sharp center for gates.',
    roll: { center_sensitivity: 200, max_rate: 500, expo: 0.0 },
    pitch: { center_sensitivity: 200, max_rate: 500, expo: 0.0 },
    yaw: { center_sensitivity: 200, max_rate: 600, expo: 0.0 },
    thr_mid: 0.55, thr_expo: 0.2, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'whoop-freestyle', name: 'Whoop Freestyle', pilotName: 'Community',
    quadType: 'whoop', rateType: 'betaflight', source: 'community',
    tags: ['whoop', 'freestyle', 'tricks', 'indoor'],
    notes: 'Indoor whoop freestyle with higher rates for flips and rolls.',
    roll: { rc_rate: 1.15, rate: 0.7, expo: 0.0 },
    pitch: { rc_rate: 1.15, rate: 0.7, expo: 0.0 },
    yaw: { rc_rate: 1.2, rate: 0.55, expo: 0.0 },
    thr_mid: 0.6, thr_expo: 0.25, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'whoop-cine', name: 'Cinewhoop Micro', pilotName: 'Community',
    quadType: 'whoop', rateType: 'actual', source: 'community',
    tags: ['whoop', 'cinematic', 'smooth', 'indoor-film'],
    notes: 'Smooth cinematic rates for micro cinewhoop — slow turns, stable footage.',
    roll: { center_sensitivity: 100, max_rate: 350, expo: 0.3 },
    pitch: { center_sensitivity: 100, max_rate: 350, expo: 0.3 },
    yaw: { center_sensitivity: 110, max_rate: 400, expo: 0.2 },
    thr_mid: 0.6, thr_expo: 0.35, createdAt: '2024-01-01T00:00:00.000Z',
  },
  // ── BEGINNERS ────────────────────────────────────────────────────
  {
    id: 'beginner-safe', name: 'Beginner Safe', pilotName: 'iFlyQuad Recommended',
    quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['beginner', 'safe', 'slow', 'learning'],
    notes: 'Low rates for beginners. Forgiving, slow, easy to control.',
    roll: { center_sensitivity: 120, max_rate: 400, expo: 0.2 },
    pitch: { center_sensitivity: 120, max_rate: 400, expo: 0.2 },
    yaw: { center_sensitivity: 90, max_rate: 300, expo: 0.1 },
    thr_mid: 0.5, thr_expo: 0.2, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'intermediate-step', name: 'Intermediate Step', pilotName: 'iFlyQuad Recommended',
    quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['intermediate', 'progression', 'medium'],
    notes: 'Good step up from beginner rates. Learning flips and rolls.',
    roll: { center_sensitivity: 160, max_rate: 540, expo: 0.1 },
    pitch: { center_sensitivity: 160, max_rate: 540, expo: 0.1 },
    yaw: { center_sensitivity: 110, max_rate: 400, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.1, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'beginner-bf', name: 'Beginner BF', pilotName: 'Community',
    quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['beginner', 'betaflight', 'learning', 'safe'],
    notes: 'Betaflight beginner rates with some expo for center softness.',
    roll: { rc_rate: 0.7, rate: 0.6, expo: 0.2 },
    pitch: { rc_rate: 0.7, rate: 0.6, expo: 0.2 },
    yaw: { rc_rate: 0.7, rate: 0.4, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.15, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'beginner-whoop', name: 'Beginner Whoop', pilotName: 'Community',
    quadType: 'whoop', rateType: 'actual', source: 'community',
    tags: ['beginner', 'whoop', 'learning', 'safe'],
    notes: 'Safe whoop rates for first-time flyers. Low rates, high expo.',
    roll: { center_sensitivity: 100, max_rate: 380, expo: 0.3 },
    pitch: { center_sensitivity: 100, max_rate: 380, expo: 0.3 },
    yaw: { center_sensitivity: 120, max_rate: 450, expo: 0.2 },
    thr_mid: 0.6, thr_expo: 0.3, createdAt: '2024-01-01T00:00:00.000Z',
  },
  // ── LONG RANGE ───────────────────────────────────────────────────
  {
    id: 'longrange-cruising', name: 'Long Range Cruise', pilotName: 'Generic LR',
    quadType: 'longrange', rateType: 'actual', source: 'community',
    tags: ['longrange', 'cruising', 'stable', 'efficient'],
    notes: 'Stable and predictable for long range cruising. Low max rate.',
    roll: { center_sensitivity: 130, max_rate: 420, expo: 0.2 },
    pitch: { center_sensitivity: 130, max_rate: 380, expo: 0.2 },
    yaw: { center_sensitivity: 100, max_rate: 300, expo: 0.1 },
    thr_mid: 0.55, thr_expo: 0.2, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'longrange-explore', name: 'Explorer LR', pilotName: 'Community',
    quadType: 'longrange', rateType: 'actual', source: 'community',
    tags: ['longrange', 'exploring', 'scenic', 'mountain'],
    notes: 'Slightly higher rates for exploring — need some agility for wind.',
    roll: { center_sensitivity: 150, max_rate: 480, expo: 0.15 },
    pitch: { center_sensitivity: 150, max_rate: 440, expo: 0.15 },
    yaw: { center_sensitivity: 110, max_rate: 340, expo: 0.1 },
    thr_mid: 0.55, thr_expo: 0.15, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'longrange-cine', name: 'LR Cinematic', pilotName: 'Community',
    quadType: 'longrange', rateType: 'actual', source: 'community',
    tags: ['longrange', 'cinematic', 'filming', 'smooth'],
    notes: 'Long range cinematic — ultra smooth for scenic filming at distance.',
    roll: { center_sensitivity: 90, max_rate: 350, expo: 0.35 },
    pitch: { center_sensitivity: 90, max_rate: 320, expo: 0.35 },
    yaw: { center_sensitivity: 70, max_rate: 250, expo: 0.25 },
    thr_mid: 0.55, thr_expo: 0.3, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'longrange-bf', name: 'LR Betaflight', pilotName: 'Community',
    quadType: 'longrange', rateType: 'betaflight', source: 'community',
    tags: ['longrange', 'betaflight', 'cruising'],
    notes: 'Betaflight long range rates with expo for smooth center.',
    roll: { rc_rate: 0.7, rate: 0.55, expo: 0.25 },
    pitch: { rc_rate: 0.7, rate: 0.5, expo: 0.25 },
    yaw: { rc_rate: 0.6, rate: 0.35, expo: 0.1 },
    thr_mid: 0.55, thr_expo: 0.2, createdAt: '2024-01-01T00:00:00.000Z',
  },
  // ── SNAP / HIGH RATE ─────────────────────────────────────────────
  {
    id: 'snap-1080', name: '1080 Snap Style', pilotName: 'Generic Snap',
    quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['snap', 'high-rate', '1080', 'aggressive', 'expert'],
    notes: '1080 deg/s for ultra-fast snaps. Requires mastery.',
    roll: { rc_rate: 1.35, rate: 0.75, expo: 0.0 },
    pitch: { rc_rate: 1.35, rate: 0.75, expo: 0.0 },
    yaw: { rc_rate: 1.1, rate: 0.6, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'snap-ultra', name: 'Ultra Snap 1200', pilotName: 'Community',
    quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['snap', 'ultra', 'expert-only', '1200+'],
    notes: 'Extreme rates for expert snap freestyle. 1200°/s roll.',
    roll: { center_sensitivity: 240, max_rate: 1200, expo: 0.0 },
    pitch: { center_sensitivity: 240, max_rate: 1200, expo: 0.0 },
    yaw: { center_sensitivity: 160, max_rate: 600, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  // ── SPECIAL / NICHE ──────────────────────────────────────────────
  {
    id: 'apex-racer', name: 'Apex Racer', pilotName: 'Community',
    quadType: 'racing', rateType: 'actual', source: 'community',
    tags: ['racing', 'apex', 'smooth-corners'],
    notes: 'Smooth corner-entry racing rates. Good for hitting apexes.',
    roll: { center_sensitivity: 190, max_rate: 520, expo: 0.1 },
    pitch: { center_sensitivity: 190, max_rate: 520, expo: 0.1 },
    yaw: { center_sensitivity: 130, max_rate: 400, expo: 0.05 },
    thr_mid: 0.45, thr_expo: 0.1, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'freestyle-hybrid', name: 'Freestyle Hybrid', pilotName: 'Community',
    quadType: 'freestyle', rateType: 'actual', source: 'community',
    tags: ['hybrid', 'versatile', 'all-around'],
    notes: 'Works for both racing and freestyle. Jack of all trades, master of none.',
    roll: { center_sensitivity: 185, max_rate: 620, expo: 0.05 },
    pitch: { center_sensitivity: 185, max_rate: 620, expo: 0.05 },
    yaw: { center_sensitivity: 125, max_rate: 440, expo: 0.0 },
    thr_mid: 0.5, thr_expo: 0.0, createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'acro-trainer', name: 'Acro Trainer', pilotName: 'Community',
    quadType: 'freestyle', rateType: 'betaflight', source: 'community',
    tags: ['training', 'acro', 'learning-tricks'],
    notes: 'Medium rates with expo for learning acro maneuvers. Forgiving center.',
    roll: { rc_rate: 0.9, rate: 0.65, expo: 0.15 },
    pitch: { rc_rate: 0.9, rate: 0.65, expo: 0.15 },
    yaw: { rc_rate: 0.85, rate: 0.45, expo: 0.05 },
    thr_mid: 0.5, thr_expo: 0.1, createdAt: '2024-01-01T00:00:00.000Z',
  },
];

/** Template for creating a new custom rate profile */
export function createEmptyRateProfile() {
  return {
    id: crypto.randomUUID(),
    name: '',
    pilotName: '',
    quadName: '',
    quadType: 'freestyle',
    rateType: 'betaflight',
    tags: [],
    notes: '',
    source: 'custom',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    roll:  { rc_rate: 1.0, rate: 0.7, expo: 0.0 },
    pitch: { rc_rate: 1.0, rate: 0.7, expo: 0.0 },
    yaw:   { rc_rate: 1.0, rate: 0.5, expo: 0.0 },
    thr_mid: 0.5,
    thr_expo: 0.0,
  };
}

const STORAGE_KEY = 'rateProfiles';

/** Load custom rate profiles from localStorage */
export function loadCustomRates() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

/** Save custom rate profiles to localStorage */
export function saveCustomRates(rates) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(rates));
  } catch {
    // ignore
  }
}
