/**
 * rateCalculator.js — Rate curve calculation + CLI generation
 * Accurate Betaflight rate formulas for all rate types.
 */

/**
 * Calculate rate curve data for a given rate profile and axis.
 * Returns array of { input (0–100%), output (deg/s) } points.
 */
export function calculateRateCurve(rateProfile, axis = 'roll', points = 100) {
  const { rateType } = rateProfile;
  const params = rateProfile[axis];
  if (!params) return [];
  const curve = [];

  for (let i = 0; i <= points; i++) {
    const input = i / points; // 0.0–1.0
    let output = 0;

    if (rateType === 'betaflight' || rateType === 'raceflight') {
      const rcRate = params.rc_rate ?? 1.0;
      const superRate = params.rate ?? 0.7;
      const expo = params.expo ?? 0.0;
      // Apply expo
      const rcCommandf = input * (expo > 0
        ? (input * input * input) * expo + input * (1 - expo)
        : input);
      // Betaflight rate formula
      const angleRate = 200.0 * rcRate * rcCommandf;
      if (superRate > 0) {
        const absRc = Math.abs(rcCommandf);
        const denom = 1.0 - (absRc * superRate);
        output = denom > 0.01 ? angleRate / denom : angleRate / 0.01;
      } else {
        output = angleRate;
      }
    } else if (rateType === 'actual') {
      const centerSens = params.center_sensitivity ?? 200;
      const maxRate = params.max_rate ?? 670;
      const expo = params.expo ?? 0.0;
      // Apply expo
      const stickDeflection = expo > 0
        ? input * ((input * input * input) * expo + input * (1 - expo)) / (input || 1)
        : input;
      const actualInput = input > 0 ? stickDeflection : 0;
      output = centerSens * actualInput + (maxRate - centerSens) * (actualInput * actualInput * actualInput);
    } else if (rateType === 'kiss') {
      const rcRate = params.rc_rate ?? 0.7;
      const superRate = params.rate ?? 0.8;
      const expo = params.expo ?? 0.0;
      const expof = input * ((input * input * input) * expo + input * (1 - expo));
      output = ((rcRate + (superRate * expof * expof)) * expof) * 1000.0 / 12.0;
    } else if (rateType === 'quick') {
      const rcRate = params.rc_rate ?? 1.0;
      const superRate = params.rate ?? 0.7;
      const expo = params.expo ?? 0.0;
      const maxRate = params.max_rate ?? 670;
      const expof = expo > 0
        ? input * ((input * input * input) * expo + input * (1 - expo))
        : input * input;
      const angleRate = rcRate * 200.0 * expof;
      if (superRate > 0) {
        output = angleRate / (1.0 - (Math.abs(expof) * superRate));
      } else {
        output = angleRate;
      }
      // QuickRates clamp to max rate
      if (maxRate) output = Math.min(output, maxRate);
    }

    curve.push({ input: Math.round(input * 100), output: Math.round(Math.abs(output)) });
  }

  return curve;
}

/**
 * Get peak rate (deg/s) at full stick deflection.
 */
export function getPeakRate(rateProfile, axis = 'roll') {
  const curve = calculateRateCurve(rateProfile, axis, 100);
  return curve.length > 0 ? curve[curve.length - 1].output : 0;
}

/**
 * Generate Betaflight CLI commands from a rate profile.
 */
export function generateRateCLI(rateProfile, rateProfileNum = 0) {
  const { rateType, roll, pitch, yaw, thr_mid, thr_expo } = rateProfile;
  const lines = [];

  lines.push(`# ═══════════════════════════════════════════════`);
  lines.push(`# Rate Profile: ${rateProfile.name || 'Custom'}`);
  if (rateProfile.pilotName) lines.push(`# Pilot: ${rateProfile.pilotName}`);
  lines.push(`# Type: ${(rateType || 'betaflight').toUpperCase()}`);
  lines.push(`# Generated by Betaflight Tuning Assist`);
  lines.push(`# ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`# ═══════════════════════════════════════════════`);
  lines.push('');
  lines.push(`rateprofile ${rateProfileNum}`);
  lines.push('');

  if (rateType === 'betaflight' || rateType === 'raceflight') {
    lines.push(`set rates_type = ${rateType === 'raceflight' ? 'RACEFLIGHT' : 'BETAFLIGHT'}`);
    lines.push(`set roll_rc_rate = ${Math.round((roll.rc_rate ?? 1.0) * 100)}`);
    lines.push(`set roll_srate = ${Math.round((roll.rate ?? 0.7) * 100)}`);
    lines.push(`set roll_expo = ${Math.round((roll.expo ?? 0.0) * 100)}`);
    lines.push(`set pitch_rc_rate = ${Math.round((pitch.rc_rate ?? 1.0) * 100)}`);
    lines.push(`set pitch_srate = ${Math.round((pitch.rate ?? 0.7) * 100)}`);
    lines.push(`set pitch_expo = ${Math.round((pitch.expo ?? 0.0) * 100)}`);
    lines.push(`set yaw_rc_rate = ${Math.round((yaw.rc_rate ?? 1.0) * 100)}`);
    lines.push(`set yaw_srate = ${Math.round((yaw.rate ?? 0.5) * 100)}`);
    lines.push(`set yaw_expo = ${Math.round((yaw.expo ?? 0.0) * 100)}`);
  } else if (rateType === 'actual') {
    lines.push(`set rates_type = ACTUAL`);
    lines.push(`set roll_rc_rate = ${Math.round(roll.center_sensitivity ?? 200)}`);
    lines.push(`set roll_srate = ${Math.round(roll.max_rate ?? 670)}`);
    lines.push(`set roll_expo = ${Math.round((roll.expo ?? 0.0) * 100)}`);
    lines.push(`set pitch_rc_rate = ${Math.round(pitch.center_sensitivity ?? 200)}`);
    lines.push(`set pitch_srate = ${Math.round(pitch.max_rate ?? 670)}`);
    lines.push(`set pitch_expo = ${Math.round((pitch.expo ?? 0.0) * 100)}`);
    lines.push(`set yaw_rc_rate = ${Math.round(yaw.center_sensitivity ?? 160)}`);
    lines.push(`set yaw_srate = ${Math.round(yaw.max_rate ?? 400)}`);
    lines.push(`set yaw_expo = ${Math.round((yaw.expo ?? 0.0) * 100)}`);
  } else if (rateType === 'kiss') {
    lines.push(`set rates_type = KISS`);
    lines.push(`set roll_rc_rate = ${Math.round((roll.rc_rate ?? 0.7) * 100)}`);
    lines.push(`set roll_srate = ${Math.round((roll.rate ?? 0.8) * 100)}`);
    lines.push(`set roll_expo = ${Math.round((roll.expo ?? 0.0) * 100)}`);
    lines.push(`set pitch_rc_rate = ${Math.round((pitch.rc_rate ?? 0.7) * 100)}`);
    lines.push(`set pitch_srate = ${Math.round((pitch.rate ?? 0.8) * 100)}`);
    lines.push(`set pitch_expo = ${Math.round((pitch.expo ?? 0.0) * 100)}`);
    lines.push(`set yaw_rc_rate = ${Math.round((yaw.rc_rate ?? 0.6) * 100)}`);
    lines.push(`set yaw_srate = ${Math.round((yaw.rate ?? 0.5) * 100)}`);
    lines.push(`set yaw_expo = ${Math.round((yaw.expo ?? 0.0) * 100)}`);
  } else if (rateType === 'quick') {
    lines.push(`set rates_type = QUICKRATES`);
    lines.push(`set roll_rc_rate = ${Math.round((roll.rc_rate ?? 1.0) * 100)}`);
    lines.push(`set roll_srate = ${Math.round((roll.rate ?? 0.7) * 100)}`);
    lines.push(`set roll_expo = ${Math.round((roll.expo ?? 0.0) * 100)}`);
    lines.push(`set pitch_rc_rate = ${Math.round((pitch.rc_rate ?? 1.0) * 100)}`);
    lines.push(`set pitch_srate = ${Math.round((pitch.rate ?? 0.7) * 100)}`);
    lines.push(`set pitch_expo = ${Math.round((pitch.expo ?? 0.0) * 100)}`);
    lines.push(`set yaw_rc_rate = ${Math.round((yaw.rc_rate ?? 1.0) * 100)}`);
    lines.push(`set yaw_srate = ${Math.round((yaw.rate ?? 0.5) * 100)}`);
    lines.push(`set yaw_expo = ${Math.round((yaw.expo ?? 0.0) * 100)}`);
  }

  lines.push('');
  lines.push(`set thr_mid = ${Math.round((thr_mid ?? 0.5) * 100)}`);
  lines.push(`set thr_expo = ${Math.round((thr_expo ?? 0.0) * 100)}`);
  lines.push('');
  lines.push('save');

  return lines.join('\n');
}
