/**
 * CLICommandsPanel.jsx — Displays individual + batch CLI commands per stage
 * Shows current → recommended values, severity indicators, copy/send actions.
 */
import { useState } from 'react';

const SEVERITY_COLOR = { critical: '#ff4444', warning: '#ffaa00', info: '#4a9eff' };
const SEVERITY_ICON  = { critical: '🔴', warning: '🟡', info: '🔵' };

export default function CLICommandsPanel({ cliCommands = [], stageTitle = '', onSendToFC }) {
  const [copiedId, setCopiedId] = useState(null);
  const [allCopied, setAllCopied] = useState(false);

  const copy = (text, id) => {
    navigator.clipboard.writeText(text).catch(() => {});
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const allCommandsText = [
    `# ${stageTitle} — Generated by Betaflight Tuning Assist`,
    '',
    ...cliCommands.map(c => `# ${c.comment}\n${c.command}`),
    '',
    'save',
  ].join('\n');

  const copyAll = () => {
    navigator.clipboard.writeText(allCommandsText).catch(() => {});
    setAllCopied(true);
    setTimeout(() => setAllCopied(false), 2500);
  };

  if (!cliCommands.length) {
    return (
      <div className="py-6 text-center text-sm text-gray-500">
        No CLI changes recommended for this stage.
      </div>
    );
  }

  return (
    <div>
      {/* Individual commands */}
      <div className="mb-4">
        <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-3 font-medium">
          Individual Commands
        </p>
        {cliCommands.map(cmd => (
          <div
            key={cmd.id}
            className="mb-2.5 p-3 bg-white/[0.02] border border-white/[0.06] rounded-r-lg"
            style={{ borderLeft: `3px solid ${SEVERITY_COLOR[cmd.severity] || '#555'}` }}
          >
            {/* Header */}
            <div className="flex justify-between items-start mb-1">
              <span className="text-xs font-semibold" style={{ color: SEVERITY_COLOR[cmd.severity] }}>
                {SEVERITY_ICON[cmd.severity]} {cmd.comment}
              </span>
            </div>

            {/* Current → Recommended */}
            {cmd.currentValue !== undefined && (
              <div className="text-[11px] text-gray-500 mb-1">
                <code className="text-gray-400">{cmd.param}</code>{' '}
                <span className="text-gray-600">current:</span>{' '}
                <code className="text-red-400/80">{cmd.currentValue ?? 'not set'}</code>{' → '}
                <span className="text-gray-600">recommended:</span>{' '}
                <code className="text-green-400/80">{cmd.recommendedValue}</code>
              </div>
            )}

            {/* Reason */}
            {cmd.reason && (
              <p className="text-[11px] text-gray-500 mb-2 leading-relaxed">{cmd.reason}</p>
            )}

            {/* Command + copy button */}
            <div className="flex gap-2 items-center">
              <code className="flex-1 block bg-[#0a0a14] px-2.5 py-1.5 rounded text-[13px] text-gray-200 font-mono">
                {cmd.command}
              </code>
              <button
                onClick={() => copy(cmd.command, cmd.id)}
                className="shrink-0 px-2.5 py-1.5 text-xs rounded bg-gray-800 hover:bg-gray-700 text-gray-300 transition-colors"
              >
                {copiedId === cmd.id ? '✅ Copied' : '📋 Copy'}
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Batch / Copy All block */}
      <div className="p-3.5 bg-[#080814] border border-[#1e2a4a] rounded-lg">
        <p className="text-[10px] text-blue-400 uppercase tracking-wider mb-2.5 font-medium">
          💻 All Commands — Paste into Betaflight CLI
        </p>
        <pre className="text-xs text-gray-400 whitespace-pre-wrap break-all font-mono leading-relaxed max-h-48 overflow-y-auto mb-3">
          {allCommandsText}
        </pre>
        <div className="flex gap-2 flex-wrap">
          <button
            onClick={copyAll}
            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
              allCopied
                ? 'bg-emerald-900/60 text-emerald-200'
                : 'bg-blue-900/40 hover:bg-blue-900/60 text-blue-200'
            }`}
          >
            {allCopied ? '✅ Copied!' : '📋 Copy All Commands'}
          </button>
          {onSendToFC && (
            <button
              onClick={() => onSendToFC(allCommandsText)}
              className="px-4 py-2 rounded-md text-sm font-medium bg-green-900/30 border border-green-700/40 text-green-400 hover:bg-green-900/50 transition-colors"
            >
              ▶ Send to FC via CLI
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
